name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        swift: ["6.1"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@682457186b71c25a884c45c06f859febbe259240
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
