name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  tests:
    name: Tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_macos_checks: true
      macos_xcode_versions: '["16.3"]'
      linux_swift_versions: '["6.1", "nightly-6.2"]'
      windows_swift_versions: '["6.1", "nightly-6.2"]'
  format:
    name: Format
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@682457186b71c25a884c45c06f859febbe259240
        with:
          swift-version: "6.1"
      - uses: actions/checkout@v4
      - name: Format
        run: swift format lint **/*.swift -r -s
